# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20170921_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='tel',
            field=models.CharField(default='SOME STRING', max_length=128),
        ),
    ]
