# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171222_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
