# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to='products_images/'),
        ),
    ]
