# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171222_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
