# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180104_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
