# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bar',
        ),
    ]
