# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-09 12:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180206_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=()),
            preserve_default=False,
        ),
    ]
