# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_postcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(height_field=100, upload_to='post_images/', width_field=100),
        ),
    ]
