# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180323_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(upload_to='post_images/'),
        ),
    ]
