# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180323_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(upload_to='products_image/'),
        ),
    ]
