# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20180405_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(blank=True, default=None, max_length=64, null=True, verbose_name='Транслит'),
        ),
    ]
