# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20171028_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nmb',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_per_item',
        ),
    ]
