# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 21:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171028_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('datetime', models.DateTimeField(verbose_name='Дата публикации')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Описание страницы Заказать',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
