# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180106_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpost',
            options={'verbose_name': 'Описание', 'verbose_name_plural': 'Описание'},
        ),
        migrations.AddField(
            model_name='orderpost',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
