# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180108_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpost',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='orderpost',
            name='session_key',
        ),
    ]
