# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 21:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180108_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
    ]
