# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180109_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpost',
            name='title',
        ),
    ]
