# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 22:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180109_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpost',
            name='description',
        ),
        migrations.AddField(
            model_name='orderpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpost',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpost',
            name='title',
            field=models.CharField(default='', max_length=68),
            preserve_default=False,
        ),
    ]
