# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180109_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpost',
            options={'verbose_name': 'Описание'},
        ),
    ]
