# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 23:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180109_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpost',
            options={'verbose_name': 'Описание', 'verbose_name_plural': 'Описания'},
        ),
        migrations.AlterField(
            model_name='orderpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpost',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
