# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-23 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Ordercontact',
        ),
    ]
