# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-23 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180223_0622'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordercontact',
            table='ordercontact',
        ),
    ]
