# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-23 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180223_0623'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordercontact',
            table='contact',
        ),
    ]
