# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 19:21
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180104_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True),
        ),
    ]
