# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='second_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
