# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180217_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
