# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
